const COLUMNS = ['Cutomer', 'Date', 'Description', 'Module', 'SCM Owner', 'RD Owner', 'How to Handle by SCM Team', 'Lesson Learn'];
const STORAGE_KEY = 'scm-control-room-issues-v2';
const LANGUAGE_KEY = 'scm-control-room-language';
const COLUMN_KEYS = { Cutomer: 'customer', Date: 'date', Description: 'description', Module: 'module', 'SCM Owner': 'scmOwner', 'RD Owner': 'rdOwner', 'How to Handle by SCM Team': 'handling', 'Lesson Learn': 'lessonLearned' };
const translations = {
  'zh-Hant': {
    subtitle: '供應鏈客戶問題與處理經驗追蹤', language: '語言', downloadTemplate: '下載 Excel 範本', importExcel: '匯入 Excel', exportData: '匯出資料', issueSummary: '資料摘要', totalIssues: '追蹤案件', currentDataset: '目前資料集', customerCount: '客戶數', customersTracked: '已追蹤客戶', moduleCount: '模組數', activeModules: '涉及產品模組', scmOwnerCount: 'SCM 負責人', activeOwners: '處理責任歸屬', filters: '資料篩選', clear: '清除', keyword: '關鍵字', searchPlaceholder: '客戶、問題描述、負責人', customer: '客戶', allCustomers: '全部客戶', module: '模組', allModules: '全部模組', scmOwner: 'SCM 負責人', allScmOwners: '全部 SCM 負責人', issueNote: '資料來自 SCM 追蹤工作表', issueList: '案件清單', addIssue: '新增案件', date: '日期', description: '問題描述', rdOwner: 'RD 負責人', handling: 'SCM 處理方式', lessonLearned: '經驗學習', actions: '操作', emptyState: '尚無符合條件的資料。請匯入 Excel 或新增案件。', close: '關閉', cancel: '取消', save: '儲存資料', edit: '編輯', newIssue: '新增案件', editIssue: '編輯 {item}', importSuccess: '已匯入 {count} 筆案件，並儲存於此瀏覽器。', importFailed: '匯入失敗：{message}', missingColumns: '缺少欄位：{columns}', noValidRows: '找不到可匯入的有效資料列。', readFailed: '無法讀取此檔案。', xlsxUnavailable: 'Excel 功能載入失敗，請確認網路連線後重新整理頁面。', noExportRows: '目前沒有可匯出的資料。', added: '已新增案件。', updated: '已更新案件。', templateFile: 'SCM_Issue_範本.xlsx', exportFile: 'SCM_Issue_追蹤資料.xlsx', sheetName: 'SCM Issue Tracking'
  },
  en: {
    subtitle: 'Customer issues and resolution lessons for SCM teams', language: 'Language', downloadTemplate: 'Download Excel template', importExcel: 'Import Excel', exportData: 'Export data', issueSummary: 'Issue summary', totalIssues: 'Tracked issues', currentDataset: 'Current dataset', customerCount: 'Customers', customersTracked: 'Customers tracked', moduleCount: 'Modules', activeModules: 'Product modules involved', scmOwnerCount: 'SCM owners', activeOwners: 'Assigned ownership', filters: 'Filters', clear: 'Clear', keyword: 'Keyword', searchPlaceholder: 'Customer, description, owner', customer: 'Customer', allCustomers: 'All customers', module: 'Module', allModules: 'All modules', scmOwner: 'SCM owner', allScmOwners: 'All SCM owners', issueNote: 'Source: SCM issue tracking worksheet', issueList: 'Issue log', addIssue: 'Add issue', date: 'Date', description: 'Description', rdOwner: 'RD owner', handling: 'SCM handling', lessonLearned: 'Lesson learned', actions: 'Actions', emptyState: 'No records match the current filters. Import Excel or add an issue.', close: 'Close', cancel: 'Cancel', save: 'Save record', edit: 'Edit', newIssue: 'Add issue', editIssue: 'Edit {item}', importSuccess: 'Imported {count} issues and saved them in this browser.', importFailed: 'Import failed: {message}', missingColumns: 'Missing columns: {columns}', noValidRows: 'No valid records were found to import.', readFailed: 'This file could not be read.', xlsxUnavailable: 'Excel features could not load. Check the network connection and refresh the page.', noExportRows: 'There are no records to export.', added: 'Issue added.', updated: 'Issue updated.', templateFile: 'SCM_Issue_Template.xlsx', exportFile: 'SCM_Issue_Tracking.xlsx', sheetName: 'SCM Issue Tracking'
  }
};
const demoRecords = [{ Cutomer: 'Mitac', Date: '2026-08-13', Description: '範例品項', Module: 'Redfish', 'SCM Owner': 'Patrick Huang', 'RD Owner': 'Tommy Hu', 'How to Handle by SCM Team': 'Test', 'Lesson Learn': 'Test' }];
const elements = { body: document.querySelector('#inventoryTableBody'), empty: document.querySelector('#emptyState'), search: document.querySelector('#searchInput'), customer: document.querySelector('#customerFilter'), module: document.querySelector('#moduleFilter'), scmOwner: document.querySelector('#scmOwnerFilter'), notice: document.querySelector('#notice'), dialog: document.querySelector('#recordDialog'), form: document.querySelector('#recordForm'), dialogTitle: document.querySelector('#dialogTitle'), itemCount: document.querySelector('#itemCount'), customerCount: document.querySelector('#customerCount'), moduleCount: document.querySelector('#moduleCount'), scmOwnerCount: document.querySelector('#scmOwnerCount') };
let records = loadRecords();
let editingIndex = null;
let language = localStorage.getItem(LANGUAGE_KEY) === 'en' ? 'en' : 'zh-Hant';

function t(key, variables = {}) { return Object.entries(variables).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), translations[language][key] ?? key); }
function columnLabel(column) { return t(COLUMN_KEYS[column]); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]); }
function toDate(value) { if (value instanceof Date && !Number.isNaN(value.getTime())) return value.toISOString().slice(0, 10); if (typeof value === 'number' && value > 0) return new Date(Date.UTC(1899, 11, 30 + value)).toISOString().slice(0, 10); const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? String(value ?? '').trim() : parsed.toISOString().slice(0, 10); }
function normalizeRecord(row) { return Object.fromEntries(COLUMNS.map((column) => [column, column === 'Date' ? toDate(row[column]) : String(row[column] ?? '').trim()])); }
function loadRecords() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved) && saved.length ? saved : demoRecords; } catch { return demoRecords; } }
function saveRecords() { localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); }
function uniqueValues(column) { return [...new Set(records.map((record) => record[column]).filter(Boolean))].sort((left, right) => left.localeCompare(right)); }
function refreshSelect(element, column, label) { const selectedValue = element.value; const values = uniqueValues(column); element.innerHTML = `<option value="">${t(label)}</option>${values.map((value) => `<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join('')}`; element.value = values.includes(selectedValue) ? selectedValue : ''; }
function refreshFilters() { refreshSelect(elements.customer, 'Cutomer', 'allCustomers'); refreshSelect(elements.module, 'Module', 'allModules'); refreshSelect(elements.scmOwner, 'SCM Owner', 'allScmOwners'); }
function getFilteredRecords() { const query = elements.search.value.trim().toLocaleLowerCase(); return records.filter((record) => { const matchQuery = !query || COLUMNS.some((column) => record[column].toLocaleLowerCase().includes(query)); return matchQuery && (!elements.customer.value || record.Cutomer === elements.customer.value) && (!elements.module.value || record.Module === elements.module.value) && (!elements.scmOwner.value || record['SCM Owner'] === elements.scmOwner.value); }); }
function render() { const filtered = getFilteredRecords(); const locale = language === 'en' ? 'en-US' : 'zh-TW'; elements.itemCount.textContent = records.length.toLocaleString(locale); elements.customerCount.textContent = uniqueValues('Cutomer').length.toLocaleString(locale); elements.moduleCount.textContent = uniqueValues('Module').length.toLocaleString(locale); elements.scmOwnerCount.textContent = uniqueValues('SCM Owner').length.toLocaleString(locale); elements.body.innerHTML = filtered.map((record) => { const originalIndex = records.indexOf(record); return `<tr>${COLUMNS.map((column) => `<td>${escapeHtml(record[column])}</td>`).join('')}<td><button class="row-action" type="button" data-edit-index="${originalIndex}">${t('edit')}</button></td></tr>`; }).join(''); elements.empty.hidden = filtered.length > 0; }
function updateLanguage() { document.documentElement.lang = language; document.title = language === 'en' ? 'SCM Control Room' : 'SCM 控制中心'; document.querySelector('#languageSelect').value = language; document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = t(element.dataset.i18n); }); document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); }); document.querySelectorAll('[data-i18n-aria]').forEach((element) => { element.setAttribute('aria-label', t(element.dataset.i18nAria)); }); refreshFilters(); render(); }
function showNotice(message, isError = false) { elements.notice.textContent = message; elements.notice.classList.toggle('error', isError); elements.notice.hidden = false; window.clearTimeout(showNotice.timeoutId); showNotice.timeoutId = window.setTimeout(() => { elements.notice.hidden = true; }, 5000); }
function ensureXlsx() { if (window.XLSX) return true; showNotice(t('xlsxUnavailable'), true); return false; }
function exportRecords(rows, fileName) { if (!ensureXlsx()) return; const worksheet = XLSX.utils.json_to_sheet(rows.map((record) => Object.fromEntries(COLUMNS.map((column) => [column, record[column]]))), { header: COLUMNS }); worksheet['!cols'] = COLUMNS.map((column) => ({ wch: Math.max(column.length + 2, ...rows.map((record) => String(record[column] ?? '').length + 2), 14) })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, t('sheetName')); XLSX.writeFile(workbook, fileName); }
function importFile(file) { if (!ensureXlsx()) return; const reader = new FileReader(); reader.onload = (event) => { try { const workbook = XLSX.read(event.target.result, { type: 'array', cellDates: true }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rawRows = XLSX.utils.sheet_to_json(sheet, { defval: '' }); const headers = new Set(Object.keys(rawRows[0] ?? {}).map((header) => header.trim())); const missing = COLUMNS.filter((column) => !headers.has(column)); if (missing.length) throw new Error(t('missingColumns', { columns: missing.map(columnLabel).join(', ') })); const imported = rawRows.map((row) => normalizeRecord(Object.fromEntries(Object.entries(row).map(([header, value]) => [header.trim(), value])))).filter((record) => record.Cutomer && record.Description); if (!imported.length) throw new Error(t('noValidRows')); records = imported; saveRecords(); refreshFilters(); render(); showNotice(t('importSuccess', { count: imported.length })); } catch (error) { showNotice(t('importFailed', { message: error.message }), true); } }; reader.onerror = () => showNotice(t('readFailed'), true); reader.readAsArrayBuffer(file); }
function openDialog(index = null) { editingIndex = index; const record = index === null ? normalizeRecord({ Date: new Date() }) : records[index]; elements.dialogTitle.textContent = index === null ? t('newIssue') : t('editIssue', { item: record.Description }); COLUMNS.forEach((column) => { elements.form.elements[column].value = record[column] ?? ''; }); elements.dialog.showModal(); }

elements.search.addEventListener('input', render);
[elements.customer, elements.module, elements.scmOwner].forEach((element) => element.addEventListener('change', render));
document.querySelector('#clearFiltersButton').addEventListener('click', () => { elements.search.value = ''; elements.customer.value = ''; elements.module.value = ''; elements.scmOwner.value = ''; render(); });
document.querySelector('#languageSelect').addEventListener('change', (event) => { language = event.target.value; localStorage.setItem(LANGUAGE_KEY, language); updateLanguage(); });
document.querySelector('#downloadTemplateButton').addEventListener('click', () => exportRecords([normalizeRecord({ Cutomer: 'Mitac', Date: new Date(), Description: 'Example issue', Module: 'Redfish', 'SCM Owner': 'SCM Owner', 'RD Owner': 'RD Owner', 'How to Handle by SCM Team': 'Describe the SCM action', 'Lesson Learn': 'Record the lesson learned' })], t('templateFile')));
document.querySelector('#exportButton').addEventListener('click', () => { const rows = getFilteredRecords(); if (!rows.length) return showNotice(t('noExportRows'), true); exportRecords(rows, t('exportFile')); });
document.querySelector('#fileInput').addEventListener('change', (event) => { if (event.target.files[0]) importFile(event.target.files[0]); event.target.value = ''; });
document.querySelector('#addRecordButton').addEventListener('click', () => openDialog());
document.querySelector('#closeDialogButton').addEventListener('click', () => elements.dialog.close());
document.querySelector('#cancelDialogButton').addEventListener('click', () => elements.dialog.close());
elements.body.addEventListener('click', (event) => { const index = event.target.dataset.editIndex; if (index !== undefined) openDialog(Number(index)); });
elements.form.addEventListener('submit', (event) => { event.preventDefault(); const record = normalizeRecord(Object.fromEntries(new FormData(elements.form))); const isNewRecord = editingIndex === null; if (isNewRecord) records.unshift(record); else records[editingIndex] = record; saveRecords(); refreshFilters(); render(); elements.dialog.close(); showNotice(t(isNewRecord ? 'added' : 'updated')); });
updateLanguage();